In [19]:
import data_loader
import numpy as np

the_data = data_loader.load_dataset("dataset_diabetes/diabetes_data_preprocessed.csv")
outputs = ["1. Train Features:", "2. Train Labels:", "3. Valid Features:", "4. Valid Labels:", "5. Test Features:", "6. Test Labels:", "7. Label Dict:"]

for i in range(len(the_data)):
    print("\n" + outputs[i] + " --> len: " + str(len(the_data[i])) + "\n\n" + str(the_data[i]))


1. Train Features: --> len: 82433

[[28269 28269 92610462 ... 0 1 0]
 [56909 56909 162968724 ... 1 1 2]
 [56503 56503 162206526 ... 1 1 1]
 ...
 [70671 70671 203166414 ... 1 1 0]
 [12809 12809 51725166 ... 1 1 1]
 [3845 3845 22872546 ... 1 1 0]]

2. Train Labels: --> len: 82433

[0 2 0 ... 2 2 1]

3. Valid Features: --> len: 9158

[[101247 101247 436765574 ... 0 1 0]
 [2348 2348 15446892 ... 0 1 1]
 [11505 11505 47518116 ... 0 1 1]
 ...
 [89452 89452 289020042 ... 0 1 0]
 [101385 101385 438529178 ... 0 0 0]
 [23280 23280 79571748 ... 1 1 1]]

4. Valid Labels: --> len: 9158

[0 0 0 ... 1 1 1]

5. Test Features: --> len: 10175

[[51502 51502 153548118 ... 0 1 1]
 [8046 8046 37023612 ... 1 1 2]
 [50255 50255 151121442 ... 0 1 0]
 ...
 [85073 85073 269113332 ... 0 0 2]
 [8332 8332 37870290 ... 0 0 2]
 [40701 40701 126311478 ... 1 1 1]]

6. Test Labels: --> len: 10175

[0 0 0 ... 1 1 1]

7. Label Dict: --> len: 3

{'no': 0, '<30': 1, '>30': 2}


In [14]:
X_train = the_data[0]
Y_train = the_data[1]

X_val = the_data[2]
Y_val = the_data[3]

X_test = the_data[4]
Y_test = the_data[5]

In [26]:
# DECISION TREE

from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score

the_results = []

for i in range(1,101):
    temp_results = [] 
    for j in range(2,52):
        dte = DecisionTreeClassifier(max_depth=i, min_samples_split=j)
        dte.fit(X_train, Y_train)
        Y_val_predict = dte.predict(X_val)
        temp_results.append("{0:.2f}".format(accuracy_score(Y_val, Y_val_predict)))
    the_results.append(temp_results)

print(the_results)

# scores = cross_val_score(dte, X_train, Y_train, cv=10)
# print("Cross Validation score: {:.2%}".format(np.mean(scores)))

[['0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56'], ['0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56', '0.56'], ['0.57', '0.57', '0.57', '0.57', '0.57', '0.57', '0.57', '0.57', '0.57', '0.57', '0.57', '0.57', '0.57', '0.57', '0.57', '0.57', '0.57', '0.57', '0.57', '0.57', '0.57', '0.57', '0.57', '0.57', '0

In [28]:
# print("Accuracy is {0:.2f}".format(accuracy_score(Y_val, Y_val_predict)))
# print("Precision is {0:.2f}".format(precision_score(Y_val, Y_val_predict)))
# print("Recall is {0:.2f}".format(recall_score(Y_val, Y_val_predict)))
# print("AUC is {0:.2f}".format(roc_auc_score(Y_val, Y_val_predict)))

# accuracy_dte = accuracy_score(Y_val, Y_val_predict)
# precision_dte = precision_score(Y_val, Y_val_predict)
# recall_dte = recall_score(Y_val, Y_val_predict)
# auc_dte = roc_auc_score(Y_val, Y_val_predict)


In [30]:
# RANDOM FOREST

from sklearn.ensemble import RandomForestClassifier

forest = RandomForestClassifier(n_estimators = 10, max_depth=25, criterion = "gini", min_samples_split = 10)
forest.fit(X_train, Y_train)
Y_val_predict = dte.predict(X_val)
print("{0:.2f}".format(accuracy_score(Y_val, Y_val_predict)))

0.55


In [42]:
import matplotlib.pyplot as plt
import pandas as pd

feature_imports = forest.feature_importances_
most_imp_features = pd.DataFrame(feature_imports)
print(most_imp_features)

           0
0   0.099818
1   0.103025
2   0.102884
3   0.136186
4   0.023622
5   0.014467
6   0.047224
7   0.020062
8   0.041497
9   0.013229
10  0.000000
11  0.023680
12  0.021908
13  0.021278
14  0.072961
15  0.058996
16  0.057437
17  0.058893
18  0.014207
19  0.005736
20  0.015656
21  0.012254
22  0.011406
23  0.023575
